services:
  vllm:
    build:
      context: ./vllm
      dockerfile: Dockerfile
    container_name: vllm-container
    ports:
      - "8000:8000"  # vLLM API
      - "5000:5000"  # FastAPI server
    volumes:
      - ./vllm/app.py:/workspace/app.py:ro  # Ensure app.py exists before running
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"  # OpenWebUI frontend
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - vllm  # Ensure vLLM is up before starting OpenWebUI

volumes:
  open-webui:
